// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcks2s1kPULC2Nci9Fv7hJleavOWKFu8E',
    appId: '1:475281848505:web:3176400944da1b3507c368',
    messagingSenderId: '475281848505',
    projectId: 'timer-6e982',
    authDomain: 'timer-6e982.firebaseapp.com',
    storageBucket: 'timer-6e982.appspot.com',
    measurementId: 'G-EFKSLB67QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEnB3ilTi6X_GwHd3_MLXlvEADSvBtQno',
    appId: '1:475281848505:android:69ccc50f7e19928507c368',
    messagingSenderId: '475281848505',
    projectId: 'timer-6e982',
    storageBucket: 'timer-6e982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEk26iFxuJKXvvoAIdwNqh5hmPecqugyg',
    appId: '1:475281848505:ios:4527a81907084c1107c368',
    messagingSenderId: '475281848505',
    projectId: 'timer-6e982',
    storageBucket: 'timer-6e982.appspot.com',
    iosClientId: '475281848505-hul062mmp0qp0lf343kr7ceg5hthrl6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.timerImageApp',
  );
}
